dtype: bfloat16
flux_path: ../ckpt/FLUX.1-Fill-dev
model:
  add_cond_attn: false
  latent_lora: false
  union_cond_attn: true
  use_sep: false
train:
  accumulate_grad_batches: 2
  batch_size: 1
  condition_type: edit
  dataloader_workers: 5
  dataset:
    condition_size: 512
    drop_image_prob: 0.1
    drop_text_prob: 0.1
    image_size: 512
    padding: 8
    path: /data/datasets
    specific_task:
    - remove
    target_size: 512
    type: any_edit
  gradient_checkpointing: true
  lora_config:
    expert_alpha: 32
    expert_rank: 32
    init_lora_weights: gaussian
    lora_alpha: 32
    num_experts: 4
    r: 32
    target_modules: (.*x_embedder|.*(?<!single_)transformer_blocks\.[0-9]+\.norm1\.linear|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_k|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_q|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_v|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_out\.0|.*(?<!single_)transformer_blocks\.[0-9]+\.ff\.net\.2|.*single_transformer_blocks\.[0-9]+\.norm\.linear|.*single_transformer_blocks\.[0-9]+\.proj_mlp|.*single_transformer_blocks\.[0-9]+\.proj_out|.*single_transformer_blocks\.[0-9]+\.attn.to_k|.*single_transformer_blocks\.[0-9]+\.attn.to_q|.*single_transformer_blocks\.[0-9]+\.attn.to_v|.*single_transformer_blocks\.[0-9]+\.attn.to_out)
    top_k: 1
  max_steps: -1
  optimizer:
    params:
      lr: 1
      safeguard_warmup: true
      use_bias_correction: true
      weight_decay: 0.01
    type: Prodigy
  sample_interval: 1000
  save_interval: 1000
  save_path: runs
  wandb:
    project: OminiControl
use_offset_noise: false
